version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
  node_app:
    container_name: node_app
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c "npx prisma generate && npm run dev"
volumes:
  mysql:
