version: "3"
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    env_file:
      - .env.test
    volumes:
      - mysql:/var/lib/mysql
  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    env_file:
      - .env.test
    command: bash -c "npx prisma migrate deploy && npm test"
volumes:
  mysql:
